### ISSUE TITLE
Is grant_type=password still supported by any AAD API?

### ISSUE THREAD

**Issue by candlerb** [nordvall/TokenClient#1]
https://github.com/nordvall/TokenClient/wiki/OAuth-2-Resource-Owner-Password-Credentials-grant-in-AzureAd shows grant_type=password in action.

However if I try this:
- with `/{tenant}/oauth2/v2.0/token` I get "The grant is not supported by this API version"
- with `/common/oauth2/token?api-version=1.1` I get "Application '&lt;ID&gt;' is not supported for this API version."

My intended application is to validate RADIUS usernames and passwords (for wireless authentication and VPN authentication) against AAD. Is there any other way to achieve this?

**Comment by nordvall** [comment]
I would expect my examples to be outdated by now, but they still work when I try.

I could successfully get tokens with username+password from these endpoints:
- https://login.windows.net/{tenant}/oauth2/token
- https://login.windows.net/common/oauth2/token
- https://login.microsoftonline.com/{tenant}/oauth2/token
- https://login.microsoftonline.com/common/oauth2/token

The latter two seem to be encouraged nowadays. And the api-version parameter seems not to be needed anymore.

In your case you could register an application in your AzureAD called RadiusClient or something. Choose the "Native client application" option. 
Your application will automatically be granted some rights to AzureAD user information, so you could then use your application as "client" and AzureAD Graph API as "resource" in your token request. Like this:

grant_type=password&resource=https%3A%2F%2Fgraph.windows.net&client_id={guid of your application}&username=someone%40yourtenant.onmicrosoft.com&password=pwd123

**Comment by candlerb** [comment]
Thank you. Knowing that it should still work, I went ahead and tried harder...

The AAD instance I am using is actually an Office 365 domain, and I had created the application client_id at apps.dev.microsoft.com; I created it as both "Web" and "Mobile application" platforms.

I wondered if instead I need to create the app inside the Azure AD portal, which you can [enable from Office365](https://github.com/jasonjoh/office365-azure-guides/blob/master/RegisterAnAppInAzure.md)

So I created application RadiusClient2 in Azure AD. Created as a native client app, and it automatically gained some access privileges which the previous app created at apps.dev.microsoft.com did not have.

![image](https://cloud.githubusercontent.com/assets/44789/18325936/772a1b6e-753b-11e6-9171-29c2b5e4afce.png)

![image](https://cloud.githubusercontent.com/assets/44789/18325945/80dd5392-753b-11e6-914f-87ddff2fea9a.png)

Then finally I changed the resource to https://graph.windows.net as you suggested, and now it works - yay! Thanks again!
